version: '3.7'

services:
  web:
    image: forksofpower/kikori:latest
    environment:
      SECRET_KEY_BASE: whBTKkImubRyrK+FsJSgmiJjWiDBqit+4vlJqeYvEKnhQPI5BPUTI9J49yxI6//0
      DATABASE_URL: ecto://postgres:postgres@db:5432/kikori
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: kikori_db
      PGPORT: 5432
      PGHOST: db
    secrets:
      - postgres_password
    ports:
      - 4000:4000
    networks:
      - web_net
      - postgres_net
    depends_on:
      - db
    deploy:
      replicas: 1
      # mode: global

  # one Nginx container per node
  nginx:
    image: nginx:latest
    # container_name: kikori_nginx
    deploy:
      mode: global
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks: 
      - web_net
  
  # Run a single beefy instance of postgres
  db:
    image: postgres:12
    secrets:
      - postgres_password
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      # resources:
      #   reservations:
      #     memory: 128M
      #   limits:
      #     memory: 256M
    ports:
      - 5432:5432
    networks:
      - postgres_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 'kikori_db'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: /home/patrick/docker/volumes/postgres
        target: /var/lib/postgresql/data
    depends_on: 
      - web

networks:
  postgres_net:
  web_net:

secrets:
  postgres_password:
    external: true